# Netlify configuration for MangaDex Reader

[build]
  # Directory to change to before starting a build
  base = "frontend/"

  # Directory that contains the deploy-ready HTML files and assets
  publish = "build/"

  # Default build command
  command = "npm run build"

[functions]
  # Directory where serverless functions are located
  directory = "netlify/functions/"

# Redirect all requests to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (set these in Netlify UI)
# REACT_APP_FIREBASE_API_KEY
# REACT_APP_FIREBASE_AUTH_DOMAIN
# REACT_APP_FIREBASE_PROJECT_ID
# REACT_APP_FIREBASE_STORAGE_BUCKET
# REACT_APP_FIREBASE_MESSAGING_SENDER_ID
# REACT_APP_FIREBASE_APP_ID
